In [1]:
#program 1:calculate total weekly energy from a list
Kwh_used= [200,250,300,350,400,450,500,550,555]
total_energy = sum(Kwh_used)
print("Total Energy Used:",total_energy,"Kwh")

Total Energy Used: 3555 Kwh

In [2]:
#program 2:stor building usage data
building_usage={
    "CSE":100,
    "Hostel":550
}
print("Hostel used:",building_usage["Hostel"],"Kwh")

Hostel used: 550 Kwh

In [3]:
#program 3:
def calculate_bill(kwh,rate_per_unit):
  return kwh * rate_per_unit

todays_bill = calculate_bill(400,8)
print("Today's estimated bill is Rs.",todays_bill)

Today's estimated bill is Rs. 3200

In [4]:
#program 4
with open("campus_energy.csv","r")as file:
  for line in file.readlines():
    print(line.strip())

﻿Date,Building,Kwh_used,peak_hour_usage
01-10-2026,CSE,250,100
02-10-2026,AIDS,300,120
03-10-2026,AIML,350,140
04-10-2026,ECE,400,150
05-10-2026,CSE,450,160
06-10-2026,CIVIL,500,149
07-10-2026,EEE,550,190
08-10-2026,IOT,600,200
09-10-2026,MECHANICAL,650,170

In [6]:
# Import the pandas library
import pandas as pd

# load the dataset you created
df = pd.read_csv("campus_energy.csv")

#Display the first few rows of the data
print("Here is the row data:")
display(df.head())

#group the data to see total usage per building
building_total = df.groupby('Building')['Kwh_used'].sum()
print("\nTotal usage per building: ")
print(building_total)

#Generate a statucal summarry(average,min,max)of the numeric columns
print("\nStatistical Summary:")
display(df.describe())

Here is the row data:

         Date Building  Kwh_used  peak_hour_usage
0  01-10-2026      CSE       250              100
1  02-10-2026     AIDS       300              120
2  03-10-2026     AIML       350              140
3  04-10-2026      ECE       400              150
4  05-10-2026      CSE       450              160

Total usage per building:
Building
AIDS          300
AIML          350
CIVIL         500
CSE           700
ECE           400
EEE           550
IOT           600
MECHANICAL    650
Name: Kwh_used, dtype: int64

Statistical Summary:

         Kwh_used  peak_hour_usage
count    9.000000         9.000000
mean   450.000000       153.222222
std    136.930639        31.637706
min    250.000000       100.000000
25%    350.000000       140.000000
50%    450.000000       150.000000
75%    550.000000       170.000000
max    650.000000       200.000000

In [8]:
# create the README.md file an dwrite a message inside it
with open("README.md","w") as file:
  file.write("# Smart campus Energy Project\n")
  file.write("This repository contains my Week 1 hands-on python and pandas assignments.\n")
  file.write("Created by: [Ganga bhavani]")

print("README.md has been successfully creted! ")

README.md has been successfully creted!